name: currency_app
description: Currency flutter application using open API and including many advanced and not advanced flutter techniques.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utils
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^2.0.1
  flutter_screenutil: ^5.8.4
  intl: ^0.18.0

  # DI
  get_it: ^7.6.0
  injectable: ^2.3.0

  # State Management
  provider: ^6.0.5

  # UI
  go_router: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

  # DI
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
  fonts:
    - family: PTSans
      fonts:
        - asset: assets/fonts/PTSans-Regular.ttf
        - asset: assets/fonts/PTSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PTSans-Italic.ttf
          style: italic
        - asset: assets/fonts/PTSans-BoldItalic.ttf
          weight: 700
          style: italic
