/// Flutter icons AppIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow_down_filled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_outlined = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_filled = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_outlined = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_arrow_filled = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_arrow_outlined = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_filled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_outlined = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_color = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_solid = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_filled = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_outlined = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_filled = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_outlined = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_outlined = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData persone_filled = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_filled = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_outlined = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
