// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoAyZrtnJG0ufB3ER6M2p-hWwFl72LhxU',
    appId: '1:1036603978306:android:9abb11927579f5460373db',
    messagingSenderId: '1036603978306',
    projectId: 'currency-app-flutter-a854a',
    storageBucket: 'currency-app-flutter-a854a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv9BPoIPYMjcowVlLIkfcpUC531oVB7lQ',
    appId: '1:1036603978306:ios:388240fddae729820373db',
    messagingSenderId: '1036603978306',
    projectId: 'currency-app-flutter-a854a',
    storageBucket: 'currency-app-flutter-a854a.appspot.com',
    iosClientId:
        '1036603978306-4brg5mj525m3s46ccjerdrqiisktvftc.apps.googleusercontent.com',
    iosBundleId: 'com.fivenation.currencyApp',
  );
}
